---
- hosts: all
  become: yes
  become_user: root


  tasks:
    - name: Test connection
      ping: 
      

    # Install Node.JS
    - name: Setup Node repo
      shell: curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -

    - name: Install Node
      yum:
        pkg: nodejs 
        state: installed
        update_cache: yes


    # Install GIT
    - name: Install GIT
      yum:
        pkg: git 
        state: installed
        update_cache: yes


    # Copy RedisIP
    - name: Copy redis IP
      copy: src=/root/redisIP dest=/root/redisIP owner=root group=root mode=0644

    # Pull latesest STABLE code
    - name: Pull Latest code from GIT
      shell: git clone -b M3 https://github.com/sasanghavi/M3.git
      args:
          chdir: /root/

    - name: NPM install
      shell: npm install
      args:
        chdir: /root/M3/app_server


    - name: Install forever
      shell: npm install -g forever

    - name: Run Server
      shell: forever start app.js
      args:
        chdir: /root/M3/app_server

 
    - name: Add New Relic repository
      yum_repository:
        name: newrelic-repo
        description: NewRelic repo
        baseurl: https://download.newrelic.com/pub/newrelic/el5/i386/newrelic-repo-5-3.noarch.rpm

    - name: Install NewRelic MonitorD
      yum: 
        pkg: newrelic-sysmond
        state: installed
        update_cache: yes

    - name: Set Key for Monitoring
      shell: nrsysmond-config --set license_key=de6aa67291303641a6bc486f90545d3eb5af4e83

    - name: run newrelic-sysmond
      shell: /etc/init.d/newrelic-sysmond start

